### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by segunh** [shweshi/terminal-stocks#1]
Hello Team, I am new here, i ran the command below, see the result.
root@segunharuna-VirtualBox:/# npm i terminal-stocks -g                                                                                                                                         loadDep:yargs -> resolveW \ |#################################--------------------------------------------------------------------------------------------------------------------------------|
npm ERR! Linux 4.15.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "terminal-stocks" "-g"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by shwetasrivastava** [comment]
@segunh  - Try uninstalling and installing npm again. Its a problem with npm.

**Comment by segunh** [comment]
> @segunh - Try uninstalling and installing npm again. Its a problem with npm.

I will try to do that, it's a new territory for me. Thank you for the quick response.
