### ISSUE TITLE
Issue when curl

### ISSUE THREAD

**Issue by andriy-git** [shweshi/terminal-stocks#13]
I have been using your awesome tool for a while now! Worked great until a few days ago. Now I get this error when I curl terminal-stocks.shashi.dev/V  or anything else
```
clear
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>
```

**Comment by chris-hmmr** [comment]
Hi @andriy-git, for the time being you can also use 'curl https://terminal-marketdata.herokuapp.com/AAPL'

Let me know if this works for you.

Cheers,
Chris

**Comment by andriy-git** [comment]
> Let me know if this works for you.

Thank you so much @chris-hmmr, it worked like a charm.
