### ISSUE TITLE
Tickers don't seem to work.

### ISSUE THREAD

**Issue by andriy-git** [shweshi/terminal-stocks#15]
Most things I try seem to work fine.  For example:
* ^GSPC
* DX-Y.NYB
* EUR=X
* BTC-USD
* TSLA

So I am a little puzzled why VUSTX doesn't. Is there something special about this specific ticker or how Yahoo handles it? I am currently using curl  terminal-stocks version.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, looks to be some issue with a null reference. I'll look into it.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, I fixed the issue and created a new release. It looks like not all tickers provide the same data. VUSTX for example does not provide data on "Day Range", which was unaccounted for.

![image](https://user-images.githubusercontent.com/1536058/212967618-09049ffc-0aa9-466f-b952-a139fc9a4f21.png)

Should be find now.

Cheers,
Christopher

**Comment by andriy-git** [comment]
@chris-hmmr so before it would of not picked up mutual funds. Mutual funds only post ends of day price and do not have a day range. Thank you very much for the fix. You do a fantastic job.

**Comment by andriy-git** [comment]
Hey @chris-hmmr , it seems like VUSTX is again not showing anything.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, thanks for reaching out. I am aware of the issue. I am currently rewriting the code because Yahoo is changing their encryption algorithm on the data every other week. Looking into a more permanent solution.

I will let you know when I have a fix ready.

Cheers,
Christopher

**Comment by chris-hmmr** [comment]
Hi @andriy-git, I just updated the website for the fix. Should be good now, please have a look for yourself.

`curl https://terminal-stocks.dev/VUSTX`

Cheers,
Christopher

**Comment by chris-hmmr** [comment]
Was fixed in https://github.com/shweshi/terminal-stocks/commit/5405d9c937490596a84532f1a073fe9f010f83aa
