### ISSUE TITLE
Feature Request: Market open/closed

### ISSUE THREAD

**Issue by andriy-git** [shweshi/terminal-stocks#17]
I was wondering if a flag could be added that checks if the US markets are closed or open. I found this element on Yahoo Finance: 
`<span class="mk-msg svelte-hbea18" data-id="mk-msg" tabindex="-1">U.S. markets closed</span>`

**Comment by chris-hmmr** [comment]
Hi @andriy-git, thanks for opening a feature request. I'll look into the API we're currently using, if there's an option to pull data on market opening hours.

Cheers,
Christopher

**Comment by chris-hmmr** [comment]
Hi @andriy-git, I found the time to look into the API we use and if there's a property that reflects _markets open/closed_. Unfortunately I wasn't able to find one. You may want to have a look yourself at the documentation. If you find something, let me know: https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/modules/quote.md

Cheers,
Christopher

**Comment by andriy-git** [comment]
Possibly, `marketState` but that is the only thing I see. 

One has PREPRE, could mean pre market. Another has regular, could stand for open.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, thanks, I'll look into it.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, so from what I can tell marketState has two possible values, either "regular" or "PRE". This would then translate into open or closed, right?

If so, I can add a new column for this.

Cheers,
Christopher

**Comment by andriy-git** [comment]
That is a good question. I wouldn't be able to tell for sure unless I know what time they change. If you can make a test flag for it, I can do the checking on the times.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, I'll add the feature and spin up a dev environment for you do run some tests. Will get back to you.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, here's the feature added to our dev environment: https://dev.terminal-stocks.dev/aapl

Currently, there are only two states, _open_ and _closed_. Running some tests, I saw that there are actually 3 different values coming out of "marketState" property 

1. PREPRE -> outputs to "closed"
2. PRE -> outputs to "closed"
3. REGULAR -> outputs to "open"

I am currently making no distinction between PREPRE and PRE, both of them I consider as the markets being _closed_ and REGULAR being _open_. We could add a 3rd state for PRE, e.g. output that as "pre-market".

Have a look and let me know what you think about it.

**Comment by andriy-git** [comment]
Seems to be on the money with market open. Will edit this for close. Only concern is that it adds another column to the output. On a smaller terminal, like a laptop or in tmux pane the output is already big. Is it possible to have this like a flag, one that has Market State and one that doesn't.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, I'll look into it.

**Comment by andriy-git** [comment]
Close is on the money as well. 2024-07-03 is Independence Day and the market will close early. I wonder if there is another ID for when it's a short day.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, I updated the code and now have a solution where one can provide an optional parameter "ms". I have an open [PR](https://github.com/shweshi/terminal-stocks/pull/22) for @shweshi to review.

**Comment by chris-hmmr** [comment]
Hi @andriy-git, the feature is now available on production.

![image](https://github.com/shweshi/terminal-stocks/assets/1536058/dcd5dbe5-fe38-458f-9942-673280745ea4)

**Comment by andriy-git** [comment]
Thank you very much. Keep up the great work. I really do like this project.
