### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by vetobus** [shweshi/terminal-stocks#18]
https://terminal-stocks.dev/
![image](https://github.com/shweshi/terminal-stocks/assets/74520246/e109b89b-2205-45ee-8f93-a107aa95ac59)
Expired 2023-06-27

**Comment by chris-hmmr** [comment]
Hi, thank you for reaching out. I renewed the domain yesterday. Will check tonight about the certificate.

**Comment by chris-hmmr** [comment]
Hi @vetobus, should be fixed now.

Cheers,
Christopher
