### ISSUE TITLE
Broken API

### ISSUE THREAD

**Issue by shweshi** [shweshi/terminal-stocks#19]
curl https://terminal-stocks.dev/market-summary is returning.

Sorry, we couldn't find. Please check the stock ticker and provide correct one. Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback

Same for other APIs with stock tickers.

**Comment by shweshi** [comment]
@chris-hmmr looks like something has changed from Yahoo API.

**Comment by chris-hmmr** [comment]
Hi @shweshi, yes, it seems Yahoo is curtailing API access. I shall investigate if there is a way to circumvent or fix this.

**Comment by chris-hmmr** [comment]
Looks like the issue on the dependent library has been resolved, see [here](https://github.com/gadicc/node-yahoo-finance2/issues/764). I'll update the package and check locally if that fixes our issue as well.

**Comment by chris-hmmr** [comment]
Hi @shweshi, I opened a PR with a fix https://github.com/shweshi/terminal-stocks/pull/20/files. Please review.

**Comment by shweshi** [comment]
@chris-hmmr merged thanks.

**Comment by chris-hmmr** [comment]
@shweshi you're welcome. Bugfix is now live [terminal-stocks.dev/AAPL](https://terminal-stocks.dev/AAPL)

<img width="736" alt="image" src="https://github.com/shweshi/terminal-stocks/assets/1536058/bcd5851e-d6ea-49f7-81c4-5385a818a2d1">
