### ISSUE TITLE
Option for export

### ISSUE THREAD

**Issue by martin072** [shweshi/terminal-stocks#2]
Hi,

Just looked at your tool. Very nice to have something that is able to retrieve Stock info.
Would it be possible to create an option to dump this information as CSV of JSON?

**Comment by shweshi** [comment]
hi, @martin072 Thanks for having a look at terminal-stocks. Currently, there is no option to export the stock data, but it would be a nice addon, would try to add this feature on terminal-stocks soon. If you implement it or want to work on it, please let me know, PR is welcome.

Happy Coding!!!

**Comment by shweshi** [comment]
@martin072 added the support to export data as json or csv.
You can export by providing --json or --csv parameter.
`terminal-stocks --ticker <TICKER> --json`

This works with other data also like --historical, --market or --tickers


Please refer the documentation:
https://shashi.dev/terminal-stocks/#/cli?id=export-the-data

**Comment by martin072** [comment]
Wouw. that is fast. Many thanks!
