### ISSUE TITLE
error / No set-cookie header on collectConsentSubmitResponse, please report

### ISSUE THREAD

**Issue by fseoane** [shweshi/terminal-stocks#23]
Error returned when issuing **`curl -s terminal-stocks.dev/MSFT`**  
```
Sorry, we couldn't find. Please check the stock ticker and provide correct one.
 No set-cookie header on collectConsentSubmitResponse, please report
```
MSFT is a with a well-known and checked symbol so the error must be something different

**Comment by chris-hmmr** [comment]
Hi @fseoane, thank you for your submission. I will look into this.

**Comment by chris-hmmr** [comment]
Hi @fseoane, I was able to fix the problem. Please have a look if things work out on your end and close the issue if your result was satisfactory.

Cheers,
Christopher

**Comment by fseoane** [comment]
Solved!!!   thx!!!
