### ISSUE TITLE
Unsupported redirect to https://finance.yahoo.com/quote/AAPL/

### ISSUE THREAD

**Issue by fseoane** [shweshi/terminal-stocks#24]
when issuing :

`curl terminal-stocks.dev/MSFT`

I get the following error

```
Sorry, we couldn't find. Please check the stock ticker and provide correct one.
 Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.%
```

**Comment by chris-hmmr** [comment]
Hi @fseoane, thank you for reporting. There's an issue with the underlying npm package for the yahoo API. https://github.com/gadicc/node-yahoo-finance2/issues/778

I'll update the npm package and deploy the application once I have it running again locally.

Cheers,
Christopher

**Comment by chris-hmmr** [comment]
Hi @fseoane, should be good now.

Cheers,
Christopher

**Comment by fseoane** [comment]
Yes.....perfect.....100% running flawlessly
