### ISSUE TITLE
Value for "stock name" property not consistent with requested ticker 

### ISSUE THREAD

**Issue by chris-hmmr** [shweshi/terminal-stocks#9]
Hi, for the current implementation, the data retrieved for a ticker seems inconsistent.

e.g.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1536058/197345495-caa0c724-898d-423e-a48a-b42053e54a14.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1536058/197345595-7cd01625-6f6b-4039-8576-ab51863b4bde.png">

I already opened a PR to fix the issue, please have a look.

Cheers,
Christopher

**Comment by shweshi** [comment]
Closed by PR #8 Thanks.
